### ISSUE TITLE
Bug fixes - Design feedback round 2

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#1757]
### Why is this issue important?

Second round of front end search adjustments:

- [ ] Remove tab border showing on My Grants links on hover
   - [ ] Underline blue text instead on hover
- [ ] More top padding between tabs on My Grants, it's crowded
- [ ] Match left and right margin across My Grants and Grants pages
- [ ] Remove opportunity number column from My Grants table
- [ ] V align Export CSV with title row
- [ ] Remove grants total "n grants" at top of Grants table
- [ ] Align titling styles between My Grants and Grants - use the larger font currently on My Grants

### Current State

NA

### Expected State

NA

### Implementation Plan

The following functions need to be added...
