### ISSUE TITLE
Turn on production feature flag

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/usdr-gost#1789]
### Why is this issue important?

Releases the new grants-search experience

### Current State

New search experience is hidden behind a feature flag

### Expected State

Complete the following tasks and then merge this ticket:

- [ ] The new search experience has been QA'd and we are confident to release this to production. Sign-off required from @mhuang-usdr 
- [ ] Ensure that all keywords and eligibility codes are migrated to grants-saved-searches #1662 
- [ ] Turn off the old keywords digest email

If the above are complete, you are all set to merge the PR for this issue and close out the task.

### Implementation Plan

- There is a `useNewTable` feature flag that needs to be flipped to `true` in all environments.
