### ISSUE TITLE
Search Adjustments from 8/15 review

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#1797]
**Search adjustments:**  

- [ ] “Edit” saved search is inconsistent. Sometimes the values are not actually getting saved
- [ ] Delete of a saved search not working - no confirmation prompt and saved search not deleting
- [x] @as1729 Make sure My Grants is showing grants assigned to user's Agency and any grants that the Agency has added a status to
- [ ] @as1729 Power of 2 issues when clicking the same multiselect option on Eligibility Codes
- [ ] Not clear that you’re prevented from creating a new search with the same name as a previous saved search - see ticket #1369 for intended functionality
- [x] @as1729  Funding type field - surface all funding types and add multi-select dropdown for field with the following values: Grant, Cooperative Agreement, Procurement Contract, Other
- [x] Ensure bill field exists and grants are filterable
  - [x] @as1729  Add database column to grants table called `bill`
  - [x] @as1729 Ensure grants ingest is saving `bill` details on grant import
  - [x] #1706 - bill field on grants detail page, connected to bill field 
  - [x] Add Bill field to search (under 'category' field)
- [x] @as1729 #1718 - remove stats from dashboard
- [x] @as1729 Ensure Opportunity Number field is searchable (same as grant_number in the backend)
- [ ] Unit tests for Edit search endpoint
- [x] Clicking “Edit” and “Clear” links lose the current page route (possibly related to the inconsistent state management issues listed above). For example, clicking “Edit” causes the nav bar to show /#/ instead of /#/grants. #1813
- [x] “Edit” saved search is not refreshing the table @jakekreider #1813
- [x] @as1729 Keyword exclude and include by phrase not working - i.e. not excluding full phrase or individual word in phrase - should exclude full phrase between commas
- [x] @as1729 Entity codes in response strings need to be escaped for proper UTF-8 character support. Examples: 
   **Grant 349864**
       Currently: r USAID&#8217;s &#8220;Resilient Health Systems for Healthy, Resilient Communities in DRC 
       [Should be](https://www.grants.gov/web/grants/view-opportunity.html?oppId=349864): r USAID’s “Resilient Health Systems for Healthy, Resilient Communities in DRC 
   **Grant 349753**
       Currently: Locally Led Development for USAID/Nepal&#8217;s Local Works Addendum
       [Should be:](https://www.grants.gov/web/grants/view-opportunity.html?oppId=349753) Locally Led Development for USAID/Nepal’s Local Works Addendum
- [x] @as1729 Search include and exclude not consistently applying to grant title and body and should apply to both for include and exclude
- [ ] @as1729 Unit tests for paginated grants endpoint
- [x] @as1729 Agency - change field name to “agency code” in search panel - this should be a partial match (i.e. USDOJ should return any agency codes with USDOJ in it, rather than needing an exact match on the full agency code)
- [x] @as1729 Review status field - update for field selections to be: Applied, Assigned, Interested, Not Applying”

**Not blockers**
- [ ] add border to bottom of table
- [ ] Update empty results screen on My Grants search results to be - "No grants have been assigned to you yet." (empty state text on browse grants should not change)
- [ ] make pressing the enter key execute the search when the advanced search panel is open
- [x] add "or" to display between include and exclude keywords on search results page
- [ ] I’m able to save a search without entering any criteria - should be required to enter one criteria

**Comment by as1729** [comment]
This is closed in favor of: https://github.com/usdigitalresponse/usdr-gost/issues/1829
