### ISSUE TITLE
Grant Finder front-end audit enhancements

### ISSUE THREAD

**Issue by saboteurina** [usdigitalresponse/usdr-gost#1928]
### Why is this issue important?

I conducted a front-end audit of Grants Finder staging against the USDR design system and found inconsistencies.

### Current State

See audit: https://docs.google.com/spreadsheets/d/1eMSpXwsBQvis9WdrM-fNbBi0IuuCq6kAfh7-dMYdUPg/edit?usp=sharing

This applies across pages/views in the Grant Finder tool.

### Expected State

See audit: https://docs.google.com/spreadsheets/d/1eMSpXwsBQvis9WdrM-fNbBi0IuuCq6kAfh7-dMYdUPg/edit?usp=sharing

### Implementation Plan

In scope for this issue:

### General
- [ ] Look for opportunities to increase whitespace throughout app

### Buttons
- [ ] Update buttons with the appropriate color tokens added as part of https://github.com/usdigitalresponse/usdr-gost/pull/1717
- [ ] Agencies - swap 'Bulk Import' and 'Add', and update buttons to use 
- [ ] Update 'Grants.gov' button to 'View on Grants.gov' and remove link icon
- [ ] Update 'Export CSV' link to be a button
- [ ] Update navy secondary buttons to be ghost buttons
- [ ] Update button behavior for Admin Delete Agency button (cursor doesn't change to the pointer hand)
- [ ] Edit pencil button - update to brand blue and remove outline
- [ ] Reduce gap between My Saved Searches and New Search buttons

### Grant modal
- [ ] Update based on reworked design (TBD)

### Headings / Typography
- [ ] Update app name + table title heading tags to follow semantic structure
- [ ] Update 'Grants Identification Tool' to 'Federal Grant Finder'
- [ ] Update current h6 so that it's smaller than h5
- [ ] Update headings from Lora to Inter

### Search
- [ ] My Saved Searches: Update to match designs more closely (secondary text color; kebab menu button; padding)
- [ ] New Search: For dropdowns and multi-selects, update to regular hover state instead of using red/green

### Table
- [ ] Make selected tab more obvious

**Comment by ClaireValdivia** [comment]
@adele-usdr  can you confirm that this was merged to staging? I don't see the changes reflected there

**Comment by adele-usdr** [comment]
@ClaireValdivia it's there now! I think it was stuck in the deploy-to-staging workflow.

**Comment by caitlinwinner** [comment]
Looking great!
- Agree header is too big on My Grants. 
- I don't see updated buttons or color on User tab but in Claire's screen shot above it looks right.
- Header ribbon top and bottom padding can be reduced by 50%

**Comment by adele-usdr** [comment]
We have the header color change tied to the profile changes - we can remove that, if you'd like.  

Opened a new branch for the padding change and button text change. Do you also want to change the text size of Federal Grant Finder?

**Comment by ClaireValdivia** [comment]
@adele-usdr thanks for these adjustments! I think the only remaining change we need is the button color/styles on the user page as it's still green. this should match what is on the agencies page

**Comment by adele-usdr** [comment]
The button update is now on staging!
