### ISSUE TITLE
Update "Appropriations Bill" dropdown options

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2063]
### Why is this issue important?
Ticket to review if dropdown selections for Appropriations Bill field can be updated to be more clear

### Action Items

- [x] Reach out to Ethan from FFIS to ask why not all agency codes are reflected in Bill Department listings
- [x] Based on FFIS convo, consider taking department listings out of Bill dropdown and determine a way to show Department names as a multi-select drop-down
- [x] Get input from partners in CoP: seeing dropdown of department names would be helpful, and they really want to be able to exclude departments. 
- [ ] Tested in staging

### Current State
Appropriations Bill field pulls from FFIS data and shows bills as well as federal departments and independent agencies

We are currently hiding "12.005," but want to do more research to determine if it would be helpful to create rules that display the Appropriations Bill field dropdown differently than data currently coming in from FFIS. 

There is also confusion from partners as the Appropriations Bill search field includes many departments, so some partners are thinking that this means that they are searching by funding agency in the Bill field when they are not. Need to determine a path forward where it is clear to users what the search under Appropriations Bill and Agency Code is searching on

Current dropdown list in "appropriations bill" field includes both bills and departments/independent agenciees
**Bills**
- Bipartisan Safer Communities Act
- Inflation Reduction Act 
- Infrastructure, Investment, and Jobs Act
- Coronavirus

**Departments and Independent Agencies**
- Department of Agriculture
- Department of Commerce
- Department of Defense
- Department of Education
- Department of Energy
- Department of Health and Human Services
- Department of Homeland Security 
- Department of Housing and Urban Development 
- Department of Homeland Security 
- Department of Justice
- Department of Labor
- Department of the Interior
- Department of Treasury
- Department of Transportation 
- Department of Veterans Affairs 
- Consumer Product Safety Commission
- Denali Commission
- Nucleare Regulatory Commission
- Corporation for National and Community Service
- Library of Congress
- National Council on Disability
- National Foundation on the Arts and the Humanities
- National Science Foundation
- Office of National Drug Control Policy
- Environmental Protection Agency 
- National Archives and Records Administration 
- Small Business Administration
- Social Security Administration 
- National Aeronautics and Space Administration 

### Expected State
- [ ] The dropdown for "Coronavirus" should be updated to say "COVID bills"

- [ ] We expect to see the bills listed above display in the dropdown. If new values are added to FFIS data, they should display in dropdown as well
- Bipartisan Safer Communities Act
- Inflation Reduction Act 
- Infrastructure, Investment, and Jobs Act
- COVID bills

- [ ] The following should never appear in the dropdown for "Appropriations Bill" 
- Department of Agriculture
- Department of Commerce
- Department of Defense
- Department of Education
- Department of Energy
- Department of Health and Human Services
- Department of Homeland Security 
- Department of Housing and Urban Development 
- Department of Homeland Security 
- Department of Justice
- Department of Labor
- Department of the Interior
- Department of Treasury
- Department of Transportation 
- Department of Veterans Affairs 
- Consumer Product Safety Commission
- Denali Commission
- Nucleare Regulatory Commission
- Corporation for National and Community Service
- Library of Congress
- National Council on Disability
- National Foundation on the Arts and the Humanities
- National Science Foundation
- Office of National Drug Control Policy
- Environmental Protection Agency 
- National Archives and Records Administration 
- Small Business Administration
- Social Security Administration 
- National Aeronautics and Space Administration 

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
Moving this to scoping as we learned in a partner call with NJ that partners are incorrectly understanding the bill field to be a stand-in for "Funding Agency" based on the dropdown options. Updating this ticket to reflect that we need to make sure it's clear to users the distinction between Appropriations Bill and Agency Code fields.

**Comment by ClaireValdivia** [comment]
@TylerHendrickson any concerns about this issue moving to Ready? see related question in #2110 about feature flag
