### ISSUE TITLE
Add Category of Funding Activity as a search field

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2109]
### Why is this issue important?
partner request from NJ. This is also the one remaining search criteria on grants.gov that we don't have on grant finder

### Current State
Grant Finder does not include a field for Category of Funding Activity

### Expected State
- [ ] On Browse Grants tab, add a field to search panel for "Category of Funding Activity" that is a multi select dropdown (i.e. similar to Eligibility field)
- [ ] Dropdown should include all items that are on grants.gov search field (see below) 
- [ ] Users should be able to select one or more category of funding activity and have this generate results that include any of the categories selected (i.e. "or" logic)
- [ ] Grant Detail page of an individual grant, below the "Bill" line,  show "Category of Funding Activity:" with relevant selections listed. If there are none, it should display blank
- [ ] Export file from both Browse Grants and My Grants should include "Category of Funding Activity" as a column, with values showing as a delimited list (similar to eligibility column)
- [ ] When an email digest is sent for a saved search that includes a filter of the Category of Funding Activity Field, the digest should reflect all filters of the saved search (including Category of Funding Activity)

**dropdown selection list:**
Affordable Care Act 
Agriculture 
Arts (see "Cultural Affairs" in CFDA) 
Business and Commerce 
Community Development 
Consumer Protection
Disaster Prevention and Relief 
Education 
Employment, Labor and Training 
Energy
Environment
Food and Nutrition
Health
Housing 
Humanities (see "Cultural Affairs" in CFDA) 
Income Security and Social Services 
Information and Statistics 
Infrastructure Investment and Jobs Act (IIJA)
Law, Justice and Legal Services 
Natural Resources
Opportunity Zone Benefits
Other (see text field entitled "Explanation of Other Category of Funding Activity" for clarification) 
Recovery Act
Regional Development
Science and Technology and other Research and Development 
Transportation

### Implementation Plan

Requirements to implement this feature can be divided as:
1. Consume and store the "Category of Funding Activity" data being provided by `grants-ingest`
2. Create the new filter component in the search UI
3. Add support for the new data to the API's search endpoints

#### 1. Consume and store "Category of Funding Activity" data

According to our [`grants-ingest` OpenAPI spec](https://github.com/usdigitalresponse/grants-ingest/blob/main/openapi/openapi.yaml), the funding activity categories are provided by the array at `$.versions.new.funding_activity.categories` on incoming grant modification event messages. Each item in the array is a `FundingActivityCategory` object ([schema](https://github.com/usdigitalresponse/grants-ingest/blob/main/openapi/openapi.yaml#L98-L158)) that contains 2 fields: `name` and `code` (which is a standardized abbreviation).

The `mapSourceToGrant()` function of `packages/server/src/lib/grants-ingest.js` is responsible for populating row-level data in the `grants` table from one of these messages (the function is called with the data from `versions.new` of an incoming message as the `source` argument).

**Simply put:** the `mapSourceToGrant()` function needs to be updated so that values from `source.funding_activity.categories[].code` are mapped to a field on the `grant` return value. 

Notes:
- Array-based fields like these have so far been stored by concatenating identifiers into a single string, which is stored in Postgres (as opposed to, say, a separate -to-many table that gets `join`ed against during search). The mapping behavior for the `cfda_list` and `eligibility_codes` fields in `mapSourceToGrant()` may serve as reference examples.
- Currently, no column exists for this value. Therefore, **a Knex migration is needed** to add a new (`text`-type) column to the `grants`, e.g. `grants.funding_activity_categories`.
- These changes will only include new data (i.e. from grants published or updated after roll-out). If we need historical data, we'll need to schedule a backfill operation from `grants-ingest` as a follow-up.

#### 2. Add support for the new data to the API's search endpoints

This step includes updates to the following API routes:
- `GET /api/organizations/:organizationId/grants/next`:
  - support a new search field as request input
  - include the relevant data in response output
- `GET /api/organizations/:organizationId/grants/exportCSVNew`:
  - include the new field data in generated CSV output
- `GET /api/organizations/:organizationId/grants/:grantId/grantDetails`:
  - include the new field data in the response output

#### 3. Add components to the search UI

The following UI changes are needed:
- Add a multi-select dropdown field in the search sidebar
- Update the Grant Detail view to include the value(s) for the grant being viewed
- Update the saved search create/edit logic to serialize the new search criteria
- Update the API call to the search endpoint to incorporate the new search criteria

As mentioned above, the backend will only store the abbreviation (`code`) values, so the client-side needs to be able to map display values to the abbreviations that the API can understand. The [`FundingActivityCategory` object](https://github.com/usdigitalresponse/grants-ingest/blob/main/openapi/openapi.yaml#L98-L158)) enum values can be reimplemented in the client-side code for this purpose. Note that in the linked schema, pairs of `code` and `name` values are indexed at the same position (i.e. `Arts` corresponds to `AR`, `Opportunity Zone Benefits` corresponds to `OZ`, etc.).

**Comment by ClaireValdivia** [comment]
@TylerHendrickson in our meeting earlier today you sent a snippet of what we're getting via grants ingest already that I believe showed a breakout of the selection options from grants.gov from this field that we could use for the dropdown. I'm not able to find what you shared...would you be able to add it to this ticket? Thanks!

**Comment by ClaireValdivia** [comment]
@TylerHendrickson any additional info or implementation details needed before I move this to Ready?

**Comment by sanason** [comment]
@ClaireValdivia 

> This is also the one remaining search criteria on grants.gov that we don't have on grant finder

Could you show me which field on the grants.gov search page supports searching by category of funding activity? I'm having a hard time mapping anything I see to that exact criteria, but that's probably because I'm unfamiliar with grants terminology.

**Comment by ClaireValdivia** [comment]
yep, you got it! and yeah the terminology is confusing, let me know if you have more questions!
