### ISSUE TITLE
CPF - Output template rules generation flow

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2178]
### Why is this issue important?

We need to document the logic of rules for CPF output template as a first step in completing the CPF reporting workflow. This is a starting point for CPF work so we can document logic needed for validation rules and treasury report output. 

### Current State

CPF logic does not exist

### Expected State

**Actions needed**
- [ ] Need output template from Treasury & upload to ticket
- [ ] Joe's review and documentation of CPF logic rules
- [ ] Eng execution of logic rules

**Acceptance Criteria**

### Implementation Plan

The following functions need to be added...
