### ISSUE TITLE
My Profile Implementation Steps

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2203]
### Why is this issue important?

checklist of implementation steps needed 

### Current State

na

### Expected State

- [ ] Update training guide to reflect naming convention changes and My Profile screenshots
- [ ] Preview changes in CoP
- [ ] Determine if any communication is needed to all users
- [ ] #2130 

### Implementation Plan

The following functions need to be added...
