### ISSUE TITLE
My Profile post-prod clean-up

### ISSUE THREAD

**Issue by thelmaboamah** [usdigitalresponse/usdr-gost#2259]
### Why is this issue important?

Some checks in the code will no longer be necessary after the feature is functional in prod. Specifically, there's a conditional check in the backend getUser function that returns different user data depending on if the avatar_color column has been created. The check is necessary to avoid breaking code before the migration that adds the column is run.

Other cleanup includes removing relevant feature flags and removing old code hidden by the flags after confirming it's safe to do so.

### Current State

Conditional and feature flags are currently in the code.

### Expected State

- [ ] Remove `avatarColorExists` and only return user data that includes the avatar_color column.
- [ ] Remove uses of the feature flag myProfileEnabled
- [ ] ~~Remove uses of the feature flag newTerminologyEnabled?~~ (split this into separate ticket)

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
@TylerHendrickson are implementation details needed for this issue or is the directive in "expected state" section sufficient?

**Comment by sanason** [comment]
@ClaireValdivia I don't think this ticket requires an implementation plan, but I would like to have "Remove uses of the feature flag newTerminologyEnabled" put into a separate ticket.
