### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2377]
### Actions needed
- [x] exploration to determine what is causing this issue to identify if there are any good options to consider other than replacing the login with one-time logins - this has been completed, we found that microsoft SafeLinks were causing this issue, and short-term fix was identified - discussion from slack here: https://usdigitalresponse.slack.com/archives/C0324KDQSCR/p1704311106894439 
- [x] Implement short-term fix to allow users using Outlook to login #2430 
- [ ] assess confidence in short-term fix for the next few months in order to determine best path forward for long term fix

### Why is this issue important?
Since mid-November, partners report users receiving the error message "Login link has already been used – please resubmit your email address." when trying to login to grant finder. Received two more reports of this issue over the holidays -one from HI and one from NV

### Current State
we would expect this error message if the user clicks the link on more than one device (i.e. clicks to send the one-time password and clicks the link from the email app on their phone, then clicks the link again from their desktop computer). we have followed up with the partner reporting the issue to see if this is happening when users are clicking the link in multiple devices. If they are only clicking the link in one device, it is possible that email apps on other devices are "using" the login code when they preview the message, and we may need to investigate the current tooling that should prevent this preview and prefetching, and/or consider switching to emailed one-time login codes rather than magic links. 

Update 12/22 - 
Isabel from Hawaii confirmed experiencing this issue and she is not logged into her work account on any other device. Also Shana from Nevada reported that clearing the cache from the browser resolved the issue.

Email from Isabel (HI):
I’m not signed into my work email on any other device, so I’m not sure whether that’s the issue either. I will say that the issue resolved pretty quickly on my end. Some of the other users who received this error message reported getting stuck in a loop of receiving the error message, resubmitting their email, receiving a new link, receiving the same error message when they click on the new link, etc. For me, I only had to resubmit my email once and then the new link I received took me to the grants finder. Hopefully that all makes sense!

Update 1/3 - Ohio ARPA Partner (Jessica) reported this issue for arpa - same error page, and the one-time login link seems to direct to the grant finder login page

### Expected State
tbd

### Implementation Plan
The following functions need to be added...

**Comment by ClaireValdivia** [comment]
discussion and brainstorming about potential solutions (i.e. change to login codes rather than one-time link) in slack thread here: https://usdigitalresponse.slack.com/archives/C05GD4B55J9/p1702677964015509

**Comment by ClaireValdivia** [comment]
This PR has been implemented in prod - https://github.com/usdigitalresponse/usdr-gost/pull/2430

TBD on longer term solution for login

**Comment by ClaireValdivia** [comment]
Closing in favor of #3878 and #3879
