### ISSUE TITLE
Grant Details Display Adjustments

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2558]
### Why is this issue important?

**Adjustments needed to new grant details page to match designs**
Design reference: https://www.figma.com/file/yQx55VTr5awPYClHIJCz8y/Grant-Details?type=design&node-id=1618-13444&mode=design&t=iBP3jszO1uuLdWSm-4

### Current State

A first pass at the new grant details page is completed, but there are some outstanding items to complete

### Expected State

**Tasks**
- [ ] match size and padding to reflect what is described in design file
- [ ] In the "copy link" button, update icon to use "copy" instead of "front" icon
- [ ] Update "clear" buttons for assigned team and status to match design (i.e. the X next to the assignment or status once it is assigned)
- [ ] Update "Choose team" and "Choose status" dropdowns to have consistent appearance, maintaining support for option categories.
- [ ] Implement "Successfully Copied" button change on Copy Link button

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
claire to separate out into two issues

**Comment by ClaireValdivia** [comment]
Mouna confirmed that padding, sizing, and clear buttons look good in staging! 

Caitlin has described some adjustments to button size and styles [here](https://usdigitalresponse.slack.com/archives/C05GD4B55J9/p1707832163481079) but we will address in a separate issue.
