### ISSUE TITLE
Grant Details Formatting Updates

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2718]
### Why is this issue important?

adjustments to clean up formatting and display on grant details page

### Current State

na

### Expected State

- [ ] On grant detail pages, the Award Ceiling number should be formatted to be currency (i.e. currently displays as 50000; it should be "$50,000" - this will be consistent with the display on the results tables
- [ ] the values displayed for Opportunity Status (i.e. Posted, Closed, Archived) should be updated to be capitalized
- [ ] under team status, the mailto: links on the emails should open in a new tab

### Implementation Plan

The following functions need to be added...

**Comment by ClaireValdivia** [comment]
@jeffsmohan are you able to draft implementation details for this one as well please?

**Comment by jeffsmohan** [comment]
@ClaireValdivia implementation details added!

**Comment by ClaireValdivia** [comment]
took out opening mailto link in new tab as we will be opening a new issue for copying the email instead. posting the implementation details for mailto in a new tab just in case we need it later
**Email in new tab**: Add a `target="_blank"` attribute to the mailto link here: https://github.com/usdigitalresponse/usdr-gost/blob/9856006dbad9ff47bd87679681bc4de1405eb61d/packages/client/src/views/GrantDetails.vue#L141

**Comment by ClaireValdivia** [comment]
This looks great in staging!
