### ISSUE TITLE
Input File Update Requests - q1 2024

### ISSUE THREAD

**Issue by ClaireValdivia** [usdigitalresponse/usdr-gost#2748]
### Why is this issue important?

- [x] Is there a better way to enable copy/pasting data between sheets that doesn't remove formatting or conditional logic? Users especially want to be able to copy address information from the subrecipient tab to the subaward tab
- [x] In Subrecipient tab, column P (Recipient SAM.gov Registration?) Add "N/A" option to dropdown. Selecting this will not open conditional fields (i.e. same behavior as if they select Yes). The NA option should never be selected when the subrecipient type (column F) = subrecipient or beneficiary, but expectation will be for partners to train on this (i.e. system will not change options for column P based on column F)
- [x] Awards tab on row 39 and below, for the subaward type column (column J), dropdown does not include full picklist - only has first four options displaying

### Current State

See above.

### Expected State

- [x] There is no way to alter copy & paste. The users simply cannot paste into dropdown columns without legitimate values (as expected and required).
- [x] "N/A" has been to Recipient SAM.gov Registration? options. The subsequent formulas that depend on the response have also been updated.
- [x] Corrected the validation (dropdown) for the Subaward Type column so that all cells in the column display all the options.

### Implementation Plan

The following functions need to be added...

**Comment by jcomeau1** [comment]
I have updated the description and what was done. I have created v20240308, tested it, and put it out on Google Drive. I'll send it to the partners.

**Comment by jcomeau1** [comment]
@ajhyndman @tzinckgraf, withe the change in values for Subrecipients, column P (Yes, No, N/A), does anything on the backend need to be updated to accept the N/A value?

**Comment by ClaireValdivia** [comment]
@jcomeau1 the subaward type looks good to me! 

The N/A field selection looks good to me, but it seems like the conditional logic for Yes and No was flipped - I had noted that "No" would be the only selection to open conditional fields and that "Yes" would not open conditional fields (and confirmed that's how it was in previous version of the input template), but it's backwards in the v20240308 template. Curious if this change was intentional.

**Comment by ClaireValdivia** [comment]
also confirmed that if you select NA, you get an error on upload. will open another issue for this 

![image](https://github.com/usdigitalresponse/usdr-gost/assets/136839582/ba3453f1-ac30-4066-82dc-f146e5731bc1)

**Comment by jcomeau1** [comment]
I must have flipped the logic. Only "No" should require entry of the other fields. I'll take a peek.

**Comment by jcomeau1** [comment]
@ClaireValdivia I have fixed the issue with SAM.gov field. I did not change the version number, but I updated Google Drive accordingly.

**Comment by ClaireValdivia** [comment]
It looks good to me! Wondering though if we wait to send out to partners until #2754 is completed

**Comment by ClaireValdivia** [comment]
closing as updated template was reviewed with partners and emailed on 3/14

**Comment by jcomeau1** [comment]
Closing per Claire on 3/18.
